version: "3.5"

services:
  database:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./init-database.sql:/docker-entrypoint-initdb.d/init-database.sql
      - pg_data:/var/lib/postgresql/data
  # chroma:
  #   image: ghcr.io/chroma-core/chroma:latest
  #   volumes:
  #     - index_data:/chroma/.chroma/index
  #   ports:
  #     - 8000:8000
  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - 6333:6333
    volumes:
      - qdrant_storage:/qdrant/storage

volumes:
  pg_data:
  index_data:
  qdrant_storage:
