# fly.toml app configuration file generated for buildel-api on 2023-09-01T11:13:31+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "buildel-api"
primary_region = "waw"
kill_signal = "SIGTERM"
swap_size_mb = 512

[build]
  dockerfile = "./Dockerfile"

[deploy]
  release_command = "/app/bin/migrate"

[env]
  PHX_HOST = "buildel-api.fly.dev"
  PORT = "8080"
  QDRANT_DATABASE_URL = "http://buildel-vectordb.internal"
  SEARCH_DB_URL = "http://buildel-searchdb.fly.dev"
  ECTO_IPV6 = true

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]
  [http_service.concurrency]
    type = "connections"
    hard_limit = 1000
    soft_limit = 1000
