name: API Test
on:
  push:
    branches:
      - main
    paths:
      - 'apps/api/**'

defaults:
  run:
    working-directory: apps/api

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    services:
      postgres:
        image: ankane/pgvector:latest
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres

    steps:
      - uses: actions/checkout@v4
      - uses: erlef/setup-beam@v1
        with:
          otp-version: '26'
          elixir-version: '1.16.1'
      - run: mix deps.get
      - run: mix test
        env:
          POSTGRES_HOST: postgres
          POSTGRES_PORT: 5432
