name: Web Release
on:
  push:
    branches:
      - main
    paths:
      - "apps/web-remix/**"
  release:
    types: [published]

defaults:
  run:
    working-directory: apps/web-remix

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 8.15.3
      - uses: actions/setup-node@v4
        with:
          node-version: "21.6.2"
          cache: "pnpm"
          cache-dependency-path: apps/web-remix/pnpm-lock.yaml
      - run: pnpm install
      - run: pnpm lint
      - run: pnpm test
      - run: pnpm build

      - name: Build and Push Docker Image
        uses: ./.github/actions/docker-build-push
        with:
          context: apps/web-remix
          dockerfile: Dockerfile
          image_name: ghcr.io/${{ github.repository }}/web-remix
          tag: ${{ github.event_name == 'release' && github.event.release.tag_name || 'alpha' }}
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - uses: superfly/flyctl-actions/setup-flyctl@master
        if: ${{ github.event_name == 'push' }}
      - run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.BUILDEL_WEB__FLY_API_TOKEN }}
        if: ${{ github.event_name == 'push' }}
